<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\DataObject\Import\Resolver\Filename' shared autowired service.

return $this->services['Pimcore\DataObject\Import\Resolver\Filename'] = new \Pimcore\DataObject\Import\Resolver\Filename(${($_ = isset($this->services['Pimcore\Model\Factory']) ? $this->services['Pimcore\Model\Factory'] : $this->load('getFactoryService.php')) && false ?: '_'});
