<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'presta_sitemap.dump_command' shared service.

return $this->services['presta_sitemap.dump_command'] = new \Presta\SitemapBundle\Command\DumpSitemapsCommand();
