<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.web_path_resolver' shared autowired service.

return $this->services['pimcore.web_path_resolver'] = new \Pimcore\HttpKernel\WebPathResolver();
