<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.data_object.import.operator.factory.base64' shared autowired service.

return $this->services['pimcore.data_object.import.operator.factory.base64'] = new \Pimcore\DataObject\Import\ColumnConfig\Operator\Factory\DefaultOperatorFactory('Pimcore\\DataObject\\Import\\ColumnConfig\\Operator\\Base64');
