<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.templating.view_helper.translate' shared autowired service.

$this->services['pimcore.templating.view_helper.translate'] = $instance = new \Pimcore\Templating\Helper\Translate(${($_ = isset($this->services['Pimcore\Translation\Translator']) ? $this->services['Pimcore\Translation\Translator'] : $this->getTranslatorService()) && false ?: '_'});

$instance->setDomain('messages');

return $instance;
