<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.custom_report.adapter.factories' shared autowired service.

return $this->services['pimcore.custom_report.adapter.factories'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('analytics' => function () {
    return ${($_ = isset($this->services['pimcore.custom_report.adapter.factory.analytics']) ? $this->services['pimcore.custom_report.adapter.factory.analytics'] : $this->services['pimcore.custom_report.adapter.factory.analytics'] = new \Pimcore\Model\Tool\CustomReport\Adapter\DefaultCustomReportAdapterFactory('Pimcore\\Model\\Tool\\CustomReport\\Adapter\\Analytics')) && false ?: '_'};
}, 'sql' => function () {
    return ${($_ = isset($this->services['pimcore.custom_report.adapter.factory.sql']) ? $this->services['pimcore.custom_report.adapter.factory.sql'] : $this->services['pimcore.custom_report.adapter.factory.sql'] = new \Pimcore\Model\Tool\CustomReport\Adapter\DefaultCustomReportAdapterFactory('Pimcore\\Model\\Tool\\CustomReport\\Adapter\\Sql')) && false ?: '_'};
}));
