<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Google\Config\SiteConfigProvider' shared autowired service.

return $this->services['Pimcore\Analytics\Google\Config\SiteConfigProvider'] = new \Pimcore\Analytics\Google\Config\SiteConfigProvider(${($_ = isset($this->services['Pimcore\Analytics\SiteId\SiteIdProvider']) ? $this->services['Pimcore\Analytics\SiteId\SiteIdProvider'] : $this->getSiteIdProviderService()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Analytics\Google\Config\ConfigProvider']) ? $this->services['Pimcore\Analytics\Google\Config\ConfigProvider'] : $this->services['Pimcore\Analytics\Google\Config\ConfigProvider'] = new \Pimcore\Analytics\Google\Config\ConfigProvider()) && false ?: '_'});
