<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail'] = new \Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail();
