#stage
deployment:
  user: root
  from: ./
  to: /opt/buildcode
  excludes:
    - var/cache
    - var/sessions
    - var/versions
    - var/config
    - web/var
releases:
  enabled: true
  max: 10
  symlink: current
  directory: releases
hosts:
  - 34.253.14.205
tasks:
  pre-deploy:
  on-deploy:
    - general/manually:
      - chmod +x confscripts/deployment_stage.sh
      - ./confscripts/deployment_stage.sh
  post-release:
  post-deploy:
