<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD7yarl6\installerProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD7yarl6/installerProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerD7yarl6.legacy');

    return;
}

if (!\class_exists(installerProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerD7yarl6\installerProdDebugProjectContainer::class, installerProdDebugProjectContainer::class, false);
}

return new \ContainerD7yarl6\installerProdDebugProjectContainer(array(
    'container.build_hash' => 'D7yarl6',
    'container.build_id' => '0451757e',
    'container.build_time' => 1531140574,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerD7yarl6');
