<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Log\ApplicationLogger' shared autowired service.

$this->services['Pimcore\Log\ApplicationLogger'] = $instance = new \Pimcore\Log\ApplicationLogger();

$instance->addWriter(${($_ = isset($this->services['Pimcore\Log\Handler\ApplicationLoggerDb']) ? $this->services['Pimcore\Log\Handler\ApplicationLoggerDb'] : $this->load('getApplicationLoggerDbService.php')) && false ?: '_'});

return $instance;
