<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.pimcore_bundle_generatorbundle_command_generatebundlecommand' shared autowired service.

return $this->services['console.command.pimcore_bundle_generatorbundle_command_generatebundlecommand'] = new \Pimcore\Bundle\GeneratorBundle\Command\GenerateBundleCommand();
