<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Http\ClientFactory' shared autowired service.

return $this->services['Pimcore\Http\ClientFactory'] = new \Pimcore\Http\ClientFactory();
