<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\DataProvider\GeoLocation' shared autowired service.

return $this->services['Pimcore\Targeting\DataProvider\GeoLocation'] = new \Pimcore\Targeting\DataProvider\GeoLocation(${($_ = isset($this->services['Pimcore\Targeting\DataProvider\GeoIp']) ? $this->services['Pimcore\Targeting\DataProvider\GeoIp'] : $this->load('getGeoIpService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
