<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\DataObject\Import\Resolver\Id' shared autowired service.

return $this->services['Pimcore\DataObject\Import\Resolver\Id'] = new \Pimcore\DataObject\Import\Resolver\Id();
