<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Piwik\EventListener\IndexSettingsListener' shared autowired service.

return $this->services['Pimcore\Analytics\Piwik\EventListener\IndexSettingsListener'] = new \Pimcore\Analytics\Piwik\EventListener\IndexSettingsListener(${($_ = isset($this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider']) ? $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] : $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] = new \Pimcore\Analytics\Piwik\Config\ConfigProvider()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Analytics\Piwik\ReportBroker']) ? $this->services['Pimcore\Analytics\Piwik\ReportBroker'] : $this->load('getReportBrokerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver']) ? $this->services['Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver'] : $this->getTokenStorageUserResolverService()) && false ?: '_'});
