<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\AdminBundle\EventListener\ImportConfigListener' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\EventListener\ImportConfigListener'] = new \Pimcore\Bundle\AdminBundle\EventListener\ImportConfigListener();
