<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\ActionHandler\Redirect' shared autowired service.

return $this->services['Pimcore\Targeting\ActionHandler\Redirect'] = new \Pimcore\Targeting\ActionHandler\Redirect();
