<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.d10iogx' shared service.

return $this->services['service_locator.d10iogx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('csv' => function () {
    $f = function (\Pimcore\Routing\Redirect\Csv $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Routing\Redirect\Csv']) ? $this->services['Pimcore\Routing\Redirect\Csv'] : $this->services['Pimcore\Routing\Redirect\Csv'] = new \Pimcore\Routing\Redirect\Csv()) && false ?: '_'});
}));
