<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'swiftmailer.mailer.newsletter_mailer.plugin.messagelogger' shared service.

return $this->services['swiftmailer.mailer.newsletter_mailer.plugin.messagelogger'] = new \Swift_Plugins_MessageLogger();
