<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.oxznqdz' shared service.

return $this->services['service_locator.oxznqdz'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('configProvider' => function () {
    $f = function (\Pimcore\Analytics\Piwik\Config\ConfigProvider $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider']) ? $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] : $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] = new \Pimcore\Analytics\Piwik\Config\ConfigProvider()) && false ?: '_'});
}, 'siteConfigProvider' => function () {
    $f = function (\Pimcore\Analytics\SiteId\SiteIdProvider $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Analytics\SiteId\SiteIdProvider']) ? $this->services['Pimcore\Analytics\SiteId\SiteIdProvider'] : $this->getSiteIdProviderService()) && false ?: '_'});
}, 'translator' => function () {
    return ${($_ = isset($this->services['Pimcore\Translation\Translator']) ? $this->services['Pimcore\Translation\Translator'] : $this->getTranslatorService()) && false ?: '_'};
}));
