<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'swiftmailer.transport.mailinvoker' shared service.

return $this->services['swiftmailer.transport.mailinvoker'] = new \Swift_Transport_SimpleMailInvoker();
