<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Http\Request\Resolver\TemplateVarsResolver' shared autowired service.

$this->services['Pimcore\Http\Request\Resolver\TemplateVarsResolver'] = $instance = new \Pimcore\Http\Request\Resolver\TemplateVarsResolver(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'});

$instance->addProvider(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\EditmodeResolver']) ? $this->services['Pimcore\Http\Request\Resolver\EditmodeResolver'] : $this->getEditmodeResolverService()) && false ?: '_'});
$instance->addProvider(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\DocumentResolver']) ? $this->services['Pimcore\Http\Request\Resolver\DocumentResolver'] : $this->getDocumentResolverService()) && false ?: '_'});

return $instance;
