<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ20ux54\installerDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ20ux54/installerDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ20ux54.legacy');

    return;
}

if (!\class_exists(installerDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ20ux54\installerDevDebugProjectContainer::class, installerDevDebugProjectContainer::class, false);
}

return new \ContainerJ20ux54\installerDevDebugProjectContainer(array(
    'container.build_hash' => 'J20ux54',
    'container.build_id' => '99ff3c19',
    'container.build_time' => 1531192353,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ20ux54');
