<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\InstallBundle\Command\ListAvailableProfilesCommand' shared autowired service.

return $this->services['Pimcore\Bundle\InstallBundle\Command\ListAvailableProfilesCommand'] = new \Pimcore\Bundle\InstallBundle\Command\ListAvailableProfilesCommand(${($_ = isset($this->services['Pimcore\Install\Profile\ProfileLocator']) ? $this->services['Pimcore\Install\Profile\ProfileLocator'] : $this->load('getProfileLocatorService.php')) && false ?: '_'});
