<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Install\Profile\ProfileLocator' shared autowired service.

return $this->services['Pimcore\Install\Profile\ProfileLocator'] = new \Pimcore\Install\Profile\ProfileLocator(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLoggerService.php')) && false ?: '_'}, new \Pimcore\Composer\PackageInfo());
