<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('Pimcore\\Bundle\\InstallBundle\\Controller\\InstallController:checkAction' => function () {
    return ${($_ = isset($this->services['service_locator.fichyx0']) ? $this->services['service_locator.fichyx0'] : $this->load('getServiceLocator_Fichyx0Service.php')) && false ?: '_'};
}, 'Pimcore\\Bundle\\InstallBundle\\Controller\\InstallController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.qzlrrlt']) ? $this->services['service_locator.qzlrrlt'] : $this->load('getServiceLocator_QzlrrltService.php')) && false ?: '_'};
}, 'Pimcore\\Bundle\\InstallBundle\\Controller\\InstallController:installAction' => function () {
    return ${($_ = isset($this->services['service_locator.fichyx0']) ? $this->services['service_locator.fichyx0'] : $this->load('getServiceLocator_Fichyx0Service.php')) && false ?: '_'};
}, 'Pimcore\\Bundle\\InstallBundle\\Controller\\InstallController::checkAction' => function () {
    return ${($_ = isset($this->services['service_locator.fichyx0']) ? $this->services['service_locator.fichyx0'] : $this->load('getServiceLocator_Fichyx0Service.php')) && false ?: '_'};
}, 'Pimcore\\Bundle\\InstallBundle\\Controller\\InstallController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.qzlrrlt']) ? $this->services['service_locator.qzlrrlt'] : $this->load('getServiceLocator_QzlrrltService.php')) && false ?: '_'};
}, 'Pimcore\\Bundle\\InstallBundle\\Controller\\InstallController::installAction' => function () {
    return ${($_ = isset($this->services['service_locator.fichyx0']) ? $this->services['service_locator.fichyx0'] : $this->load('getServiceLocator_Fichyx0Service.php')) && false ?: '_'};
})));
