<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Install\Profile\FileInstaller' shared autowired service.

return $this->services['Pimcore\Install\Profile\FileInstaller'] = new \Pimcore\Install\Profile\FileInstaller(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLoggerService.php')) && false ?: '_'}, $this->targetDirs[4]);
