<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\InstallBundle\Command\InstallCommand' shared autowired service.

return $this->services['Pimcore\Bundle\InstallBundle\Command\InstallCommand'] = new \Pimcore\Bundle\InstallBundle\Command\InstallCommand(${($_ = isset($this->services['Pimcore\Install\Installer']) ? $this->services['Pimcore\Install\Installer'] : $this->load('getInstallerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Install\Profile\ProfileLocator']) ? $this->services['Pimcore\Install\Profile\ProfileLocator'] : $this->load('getProfileLocatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
