imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: 'local/' }

pimcore:

#### REDIS CACHE
    cache:
        pools:
            redis:
                enabled: true
                connection:
                    server: localhost
                    database: 14

#### FEATURE FLAGS
#    flags:
#        zend_date: true

#### CLASS OVERRIDES EXAMPLES
#    models:
#        class_overrides:
#            'Pimcore\Model\DataObject\News': 'AppBundle\Model\DataObject\News'
#            'Pimcore\Model\DataObject\News\Listing': 'AppBundle\Model\DataObject\News\Listing'
#            'Pimcore\Model\DataObject\Folder': 'AppBundle\Model\DataObject\Folder'
#            'Pimcore\Model\Asset\Folder': 'AppBundle\Model\Asset\Folder'
#            'Pimcore\Model\Asset\Image': 'AppBundle\Model\Asset\Image'
#            'Pimcore\Model\Document\Page': 'AppBundle\Model\Document\Page'
#            'Pimcore\Model\Document\Link': 'AppBundle\Model\Document\Link'
#            'Pimcore\Model\Document\Listing': 'AppBundle\Model\Document\Listing'

doctrine:
    dbal:
        charset: utf8mb4
        driver: pdo_mysql
        host: '%database_host%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    # username:  '%mailer_user%'
    # password:  '%mailer_password%'
#    auth_mode:  '%auth_mode%'
    # encryption: '%encryption%'
    port:       '%port%'
    # spool:      { type: memory }
    # logging:    true
