<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\Command\CacheClearCommand' shared autowired service.

return $this->services['Pimcore\Bundle\CoreBundle\Command\CacheClearCommand'] = new \Pimcore\Bundle\CoreBundle\Command\CacheClearCommand();
