<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Templating\Helper\GetAllParams' shared autowired service.

return $this->services['Pimcore\Templating\Helper\GetAllParams'] = new \Pimcore\Templating\Helper\GetAllParams(${($_ = isset($this->services['Pimcore\Http\RequestHelper']) ? $this->services['Pimcore\Http\RequestHelper'] : $this->getRequestHelperService()) && false ?: '_'});
