<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\EventListener\MaintenanceListener' shared autowired service.

return $this->services['Pimcore\Targeting\EventListener\MaintenanceListener'] = new \Pimcore\Targeting\EventListener\MaintenanceListener(${($_ = isset($this->services['Pimcore\Targeting\Storage\TargetingStorageInterface']) ? $this->services['Pimcore\Targeting\Storage\TargetingStorageInterface'] : $this->getTargetingStorageInterfaceService()) && false ?: '_'});
