<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.data_object.import.operator.factory.object_brick_setter' shared autowired service.

return $this->services['pimcore.data_object.import.operator.factory.object_brick_setter'] = new \Pimcore\DataObject\Import\ColumnConfig\Operator\Factory\ObjectBrickSetterFactory(${($_ = isset($this->services['Pimcore\Model\Factory']) ? $this->services['Pimcore\Model\Factory'] : $this->load('getFactoryService.php')) && false ?: '_'});
