<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.cache.core.symfony_adapter.array' shared autowired service.

$this->services['pimcore.cache.core.symfony_adapter.array'] = $instance = new \Symfony\Component\Cache\Adapter\ArrayAdapter(2419200, false);

$instance->setLogger(${($_ = isset($this->services['monolog.logger.cache']) ? $this->services['monolog.logger.cache'] : $this->getMonolog_Logger_CacheService()) && false ?: '_'});

return $instance;
