<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.http_client' shared autowired service.

return $this->services['pimcore.http_client'] = ${($_ = isset($this->services['Pimcore\Http\ClientFactory']) ? $this->services['Pimcore\Http\ClientFactory'] : $this->services['Pimcore\Http\ClientFactory'] = new \Pimcore\Http\ClientFactory()) && false ?: '_'}->createClient();
