<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Piwik\Api\SitesManager' shared autowired service.

return $this->services['Pimcore\Analytics\Piwik\Api\SitesManager'] = new \Pimcore\Analytics\Piwik\Api\SitesManager(${($_ = isset($this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider']) ? $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] : $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] = new \Pimcore\Analytics\Piwik\Config\ConfigProvider()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Analytics\Piwik\Api\ApiClient']) ? $this->services['Pimcore\Analytics\Piwik\Api\ApiClient'] : $this->load('getApiClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Config\ReportConfigWriter']) ? $this->services['Pimcore\Config\ReportConfigWriter'] : $this->load('getReportConfigWriterService.php')) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Translation\Translator']) ? $this->services['Pimcore\Translation\Translator'] : $this->getTranslatorService()) && false ?: '_'});
