<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\DataProvider\TargetingStorage' shared autowired service.

return $this->services['Pimcore\Targeting\DataProvider\TargetingStorage'] = new \Pimcore\Targeting\DataProvider\TargetingStorage(${($_ = isset($this->services['Pimcore\Targeting\Storage\TargetingStorageInterface']) ? $this->services['Pimcore\Targeting\Storage\TargetingStorageInterface'] : $this->getTargetingStorageInterfaceService()) && false ?: '_'});
