<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\Command\Bundle\UpdateCommand' shared autowired service.

return $this->services['Pimcore\Bundle\CoreBundle\Command\Bundle\UpdateCommand'] = new \Pimcore\Bundle\CoreBundle\Command\Bundle\UpdateCommand();
