<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\ActionHandler\AssignTargetGroup' shared autowired service.

return $this->services['Pimcore\Targeting\ActionHandler\AssignTargetGroup'] = new \Pimcore\Targeting\ActionHandler\AssignTargetGroup(${($_ = isset($this->services['Pimcore\Targeting\ConditionMatcher']) ? $this->services['Pimcore\Targeting\ConditionMatcher'] : $this->getConditionMatcherService()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Targeting\Storage\TargetingStorageInterface']) ? $this->services['Pimcore\Targeting\Storage\TargetingStorageInterface'] : $this->getTargetingStorageInterfaceService()) && false ?: '_'});
