<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\AdminBundle\Session\AdminSessionBagConfigurator' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\Session\AdminSessionBagConfigurator'] = new \Pimcore\Bundle\AdminBundle\Session\AdminSessionBagConfigurator($this->parameters['pimcore.admin.session.attribute_bags']);
