<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Extension\Document\Areabrick\AreabrickManager' shared autowired service.

return $this->services['Pimcore\Extension\Document\Areabrick\AreabrickManager'] = new \Pimcore\Extension\Document\Areabrick\AreabrickManager(${($_ = isset($this->services['Pimcore\Extension\Config']) ? $this->services['Pimcore\Extension\Config'] : $this->get('Pimcore\Extension\Config')) && false ?: '_'}, new \Symfony\Component\DependencyInjection\ServiceLocator(array()));
