<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\AdminBundle\Session\Handler\AdminSessionHandler' shared autowired service.

$this->services['Pimcore\Bundle\AdminBundle\Session\Handler\AdminSessionHandler'] = $instance = new \Pimcore\Bundle\AdminBundle\Session\Handler\AdminSessionHandler(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'});

$instance->setLogger(${($_ = isset($this->services['monolog.logger.pimcore_admin.session']) ? $this->services['monolog.logger.pimcore_admin.session'] : $this->load('getMonolog_Logger_PimcoreAdmin_SessionService.php')) && false ?: '_'});

return $instance;
