<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Navigation\Renderer\Breadcrumbs' shared autowired service.

return $this->services['Pimcore\Navigation\Renderer\Breadcrumbs'] = new \Pimcore\Navigation\Renderer\Breadcrumbs(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->getTemplatingService()) && false ?: '_'});
