<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.pimcore_migrations_command_statuscommand' shared autowired service.

return $this->services['console.command.pimcore_migrations_command_statuscommand'] = new \Pimcore\Migrations\Command\StatusCommand();
