<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Templating\Helper\Cache' shared autowired service.

return $this->services['Pimcore\Templating\Helper\Cache'] = new \Pimcore\Templating\Helper\Cache(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\EditmodeResolver']) ? $this->services['Pimcore\Http\Request\Resolver\EditmodeResolver'] : $this->getEditmodeResolverService()) && false ?: '_'});
