<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Composer\Config\ConfigMerger' shared autowired service.

return $this->services['Pimcore\Composer\Config\ConfigMerger'] = new \Pimcore\Composer\Config\ConfigMerger(array(0 => ${($_ = isset($this->services['Pimcore\Composer\Config\Normalizer\EndroidQrCodeRenamedPackageNormalizer']) ? $this->services['Pimcore\Composer\Config\Normalizer\EndroidQrCodeRenamedPackageNormalizer'] : $this->services['Pimcore\Composer\Config\Normalizer\EndroidQrCodeRenamedPackageNormalizer'] = new \Pimcore\Composer\Config\Normalizer\EndroidQrCodeRenamedPackageNormalizer()) && false ?: '_'}, 1 => ${($_ = isset($this->services['Pimcore\Composer\Config\Normalizer\Php7PlatformNormalizer']) ? $this->services['Pimcore\Composer\Config\Normalizer\Php7PlatformNormalizer'] : $this->services['Pimcore\Composer\Config\Normalizer\Php7PlatformNormalizer'] = new \Pimcore\Composer\Config\Normalizer\Php7PlatformNormalizer()) && false ?: '_'}));
