<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand' shared autowired service.

return $this->services['Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand'] = new \Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
