<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\AdminBundle\Controller\Rest\ClassController' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\Controller\Rest\ClassController'] = new \Pimcore\Bundle\AdminBundle\Controller\Rest\ClassController(${($_ = isset($this->services['pimcore_admin.webservice.service']) ? $this->services['pimcore_admin.webservice.service'] : $this->services['pimcore_admin.webservice.service'] = new \Pimcore\Model\Webservice\Service()) && false ?: '_'});
