<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Routing\Redirect\Csv' shared autowired service.

return $this->services['Pimcore\Routing\Redirect\Csv'] = new \Pimcore\Routing\Redirect\Csv();
