<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Piwik\EventListener\CacheListener' shared autowired service.

return $this->services['Pimcore\Analytics\Piwik\EventListener\CacheListener'] = new \Pimcore\Analytics\Piwik\EventListener\CacheListener(${($_ = isset($this->services['pimcore.cache.core.handler']) ? $this->services['pimcore.cache.core.handler'] : $this->getPimcore_Cache_Core_HandlerService()) && false ?: '_'});
