<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cmf_routing.validator.route_defaults' shared service.

$a = new \Symfony\Bundle\FrameworkBundle\Templating\DelegatingEngine($this, array());
$a->addEngine(${($_ = isset($this->services['pimcore.templating.engine.php']) ? $this->services['pimcore.templating.engine.php'] : $this->getPimcore_Templating_Engine_PhpService()) && false ?: '_'});
$a->addEngine(${($_ = isset($this->services['pimcore.templating.engine.twig']) ? $this->services['pimcore.templating.engine.twig'] : $this->getPimcore_Templating_Engine_TwigService()) && false ?: '_'});

return $this->services['cmf_routing.validator.route_defaults'] = new \Symfony\Cmf\Bundle\RoutingBundle\Validator\Constraints\RouteDefaultsTemplatingValidator(${($_ = isset($this->services['controller_resolver']) ? $this->services['controller_resolver'] : $this->getControllerResolverService()) && false ?: '_'}, $a);
