<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\EventListener\Frontend\ContentTemplateListener' shared autowired service.

$this->services['Pimcore\Bundle\CoreBundle\EventListener\Frontend\ContentTemplateListener'] = $instance = new \Pimcore\Bundle\CoreBundle\EventListener\Frontend\ContentTemplateListener(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\TemplateResolver']) ? $this->services['Pimcore\Http\Request\Resolver\TemplateResolver'] : $this->load('getTemplateResolverService.php')) && false ?: '_'});

$instance->setPimcoreContextResolver(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\PimcoreContextResolver']) ? $this->services['Pimcore\Http\Request\Resolver\PimcoreContextResolver'] : $this->getPimcoreContextResolverService()) && false ?: '_'});

return $instance;
