<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Controller\Config\ControllerDataProvider' shared autowired service.

return $this->services['Pimcore\Controller\Config\ControllerDataProvider'] = new \Pimcore\Controller\Config\ControllerDataProvider(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'}, $this->parameters['pimcore.service_controllers']);
