<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Sitemap\Document\DocumentTreeGenerator' shared autowired service.

return $this->services['Pimcore\Sitemap\Document\DocumentTreeGenerator'] = new \Pimcore\Sitemap\Document\DocumentTreeGenerator(new \Pimcore\Sitemap\Document\DocumentUrlGenerator(new \Pimcore\Sitemap\UrlGenerator(${($_ = isset($this->services['pimcore.routing.router.request_context']) ? $this->services['pimcore.routing.router.request_context'] : $this->getPimcore_Routing_Router_RequestContextService()) && false ?: '_'})), array(0 => new \Pimcore\Sitemap\Element\Filter\PublishedFilter(), 1 => new \Pimcore\Sitemap\Element\Filter\PropertiesFilter(), 2 => new \Pimcore\Sitemap\Document\Filter\DocumentTypeFilter(), 3 => new \Pimcore\Sitemap\Document\Filter\SiteRootFilter()), array(0 => new \Pimcore\Sitemap\Element\Processor\ModificationDateProcessor(), 1 => new \Pimcore\Sitemap\Element\Processor\PropertiesProcessor()));
