<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Document\Renderer\DocumentRenderer' shared autowired service.

$this->services['Pimcore\Document\Renderer\DocumentRenderer'] = $instance = new \Pimcore\Document\Renderer\DocumentRenderer(${($_ = isset($this->services['Pimcore\Http\RequestHelper']) ? $this->services['Pimcore\Http\RequestHelper'] : $this->getRequestHelperService()) && false ?: '_'}, ${($_ = isset($this->services['pimcore.templating.action_renderer']) ? $this->services['pimcore.templating.action_renderer'] : $this->getPimcore_Templating_ActionRendererService()) && false ?: '_'}, ${($_ = isset($this->services['fragment.renderer.inline']) ? $this->services['fragment.renderer.inline'] : $this->load('getFragment_Renderer_InlineService.php')) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Routing\Dynamic\DocumentRouteHandler']) ? $this->services['Pimcore\Routing\Dynamic\DocumentRouteHandler'] : $this->getDocumentRouteHandlerService()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Targeting\Document\DocumentTargetingConfigurator']) ? $this->services['Pimcore\Targeting\Document\DocumentTargetingConfigurator'] : $this->getDocumentTargetingConfiguratorService()) && false ?: '_'});

$instance->setEventDispatcher(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
$instance->setContainerService(${($_ = isset($this->services['pimcore.templating.view_helper.placeholder.container_service']) ? $this->services['pimcore.templating.view_helper.placeholder.container_service'] : $this->getPimcore_Templating_ViewHelper_Placeholder_ContainerServiceService()) && false ?: '_'});

return $instance;
