<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\AdminBundle\Controller\GDPR\DataObjectController' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\Controller\GDPR\DataObjectController'] = new \Pimcore\Bundle\AdminBundle\Controller\GDPR\DataObjectController();
