<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Templating\Helper\Device' shared autowired service.

return $this->services['Pimcore\Templating\Helper\Device'] = new \Pimcore\Templating\Helper\Device();
