<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\DataProvider\Device' shared autowired service.

$this->services['Pimcore\Targeting\DataProvider\Device'] = $instance = new \Pimcore\Targeting\DataProvider\Device(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});

$instance->setCache(${($_ = isset($this->services['pimcore.cache.core.handler']) ? $this->services['pimcore.cache.core.handler'] : $this->getPimcore_Cache_Core_HandlerService()) && false ?: '_'});
$instance->setCachePool(${($_ = isset($this->services['pimcore.cache.core.pool.doctrine']) ? $this->services['pimcore.cache.core.pool.doctrine'] : $this->getPimcore_Cache_Core_Pool_DoctrineService()) && false ?: '_'});

return $instance;
