<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\AdminBundle\Controller\Admin\DataObjectHelperController' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\Controller\Admin\DataObjectHelperController'] = new \Pimcore\Bundle\AdminBundle\Controller\Admin\DataObjectHelperController();
