<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\EventListener\DocumentTargetGroupListener' shared autowired service.

return $this->services['Pimcore\Targeting\EventListener\DocumentTargetGroupListener'] = new \Pimcore\Targeting\EventListener\DocumentTargetGroupListener(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\DocumentResolver']) ? $this->services['Pimcore\Http\Request\Resolver\DocumentResolver'] : $this->getDocumentResolverService()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Targeting\ActionHandler\DelegatingActionHandler']) ? $this->services['Pimcore\Targeting\ActionHandler\DelegatingActionHandler'] : $this->getDelegatingActionHandlerService()) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
