<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController'] = new \Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController(${($_ = isset($this->services['Pimcore\Extension\Bundle\PimcoreBundleManager']) ? $this->services['Pimcore\Extension\Bundle\PimcoreBundleManager'] : $this->getPimcoreBundleManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Extension\Document\Areabrick\AreabrickManager']) ? $this->services['Pimcore\Extension\Document\Areabrick\AreabrickManager'] : $this->load('getAreabrickManagerService.php')) && false ?: '_'});
