<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\Command\Bundle\EnableCommand' shared autowired service.

return $this->services['Pimcore\Bundle\CoreBundle\Command\Bundle\EnableCommand'] = new \Pimcore\Bundle\CoreBundle\Command\Bundle\EnableCommand(${($_ = isset($this->services['Pimcore\Bundle\CoreBundle\Command\Bundle\Helper\PostStateChange']) ? $this->services['Pimcore\Bundle\CoreBundle\Command\Bundle\Helper\PostStateChange'] : $this->load('getPostStateChangeService.php')) && false ?: '_'});
