<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Composer\Config\Normalizer\EndroidQrCodeRenamedPackageNormalizer' shared autowired service.

return $this->services['Pimcore\Composer\Config\Normalizer\EndroidQrCodeRenamedPackageNormalizer'] = new \Pimcore\Composer\Config\Normalizer\EndroidQrCodeRenamedPackageNormalizer();
