<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver' shared autowired service.

return $this->services['Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver'] = new \Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\EditmodeResolver']) ? $this->services['Pimcore\Http\Request\Resolver\EditmodeResolver'] : $this->getEditmodeResolverService()) && false ?: '_'});
