<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\EventListener\FullPageCacheCookieCleanupListener' shared autowired service.

return $this->services['Pimcore\Targeting\EventListener\FullPageCacheCookieCleanupListener'] = new \Pimcore\Targeting\EventListener\FullPageCacheCookieCleanupListener();
