<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\DataProvider\GeoIp' shared autowired service.

$this->services['Pimcore\Targeting\DataProvider\GeoIp'] = $instance = new \Pimcore\Targeting\DataProvider\GeoIp(new \GeoIp2\Database\Reader(($this->targetDirs[2].'/config/GeoLite2-City.mmdb')), ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});

$instance->setCache(${($_ = isset($this->services['pimcore.cache.core.handler']) ? $this->services['pimcore.cache.core.handler'] : $this->getPimcore_Cache_Core_HandlerService()) && false ?: '_'});

return $instance;
