<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Templating\Helper\HeadScript' shared autowired service.

return $this->services['Pimcore\Templating\Helper\HeadScript'] = new \Pimcore\Templating\Helper\HeadScript(${($_ = isset($this->services['pimcore.templating.view_helper.placeholder.container_service']) ? $this->services['pimcore.templating.view_helper.placeholder.container_service'] : $this->getPimcore_Templating_ViewHelper_Placeholder_ContainerServiceService()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Templating\Helper\WebLink']) ? $this->services['Pimcore\Templating\Helper\WebLink'] : $this->load('getWebLinkService.php')) && false ?: '_'});
