<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\AdminBundle\Controller\Admin\IndexController' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\Controller\Admin\IndexController'] = new \Pimcore\Bundle\AdminBundle\Controller\Admin\IndexController(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
