<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\Command\Targeting\MigrateElementNamesCommand' shared autowired service.

return $this->services['Pimcore\Bundle\CoreBundle\Command\Targeting\MigrateElementNamesCommand'] = new \Pimcore\Bundle\CoreBundle\Command\Targeting\MigrateElementNamesCommand(${($_ = isset($this->services['pimcore.document.tag.naming.strategy.nested']) ? $this->services['pimcore.document.tag.naming.strategy.nested'] : $this->services['pimcore.document.tag.naming.strategy.nested'] = new \Pimcore\Document\Tag\NamingStrategy\NestedNamingStrategy()) && false ?: '_'});
