<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\HttpKernel\CacheWarmer\MkdirCacheWarmer' shared autowired service.

return $this->services['Pimcore\HttpKernel\CacheWarmer\MkdirCacheWarmer'] = new \Pimcore\HttpKernel\CacheWarmer\MkdirCacheWarmer();
