<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.document.tag.naming.migration.strategy.analyze' shared autowired service.

return $this->services['pimcore.document.tag.naming.migration.strategy.analyze'] = new \Pimcore\Document\Tag\NamingStrategy\Migration\AnalyzeMigrationStrategy(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
