<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.document.tag.naming.strategy.nested' shared autowired service.

return $this->services['pimcore.document.tag.naming.strategy.nested'] = new \Pimcore\Document\Tag\NamingStrategy\NestedNamingStrategy();
