<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.data_object.import.value.factory.default' shared autowired service.

return $this->services['pimcore.data_object.import.value.factory.default'] = new \Pimcore\DataObject\Import\ColumnConfig\Value\Factory\DefaultValueFactory('Pimcore\\DataObject\\Import\\ColumnConfig\\Value\\DefaultValue');
