<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.implementation_loader.object.layout' shared autowired service.

return $this->services['pimcore.implementation_loader.object.layout'] = new \Pimcore\Model\DataObject\ClassDefinition\Loader\LayoutLoader(array(0 => new \Pimcore\Loader\ImplementationLoader\PrefixLoader(array(0 => '\\Pimcore\\Model\\DataObject\\ClassDefinition\\Layout\\', 1 => '\\Object_Class_Layout_'))));
