<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.document.newsletter.factory.report' shared autowired service.

return $this->services['pimcore.document.newsletter.factory.report'] = new \Pimcore\Document\Newsletter\ReportAddressSourceAdapterFactory(${($_ = isset($this->services['pimcore.custom_report.adapter.factories']) ? $this->services['pimcore.custom_report.adapter.factories'] : $this->load('getPimcore_CustomReport_Adapter_FactoriesService.php')) && false ?: '_'});
