<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.document.newsletter.factory.csv' shared autowired service.

return $this->services['pimcore.document.newsletter.factory.csv'] = new \Pimcore\Document\Newsletter\DefaultAddressSourceAdapterFactory('Pimcore\\Document\\Newsletter\\AddressSourceAdapter\\CsvList');
