<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Bundle\CoreBundle\Controller\PublicServicesController' shared autowired service.

return $this->services['Pimcore\Bundle\CoreBundle\Controller\PublicServicesController'] = new \Pimcore\Bundle\CoreBundle\Controller\PublicServicesController();
