<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Model\Schedule\Manager\Procedural' shared autowired service.

return $this->services['Pimcore\Model\Schedule\Manager\Procedural'] = new \Pimcore\Model\Schedule\Manager\Procedural('maintenance.pid', ${($_ = isset($this->services['monolog.logger.pimcore.maintenance']) ? $this->services['monolog.logger.pimcore.maintenance'] : $this->load('getMonolog_Logger_Pimcore_MaintenanceService.php')) && false ?: '_'});
