<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.data_object.grid_column_config.operator.factory.translate_value' shared autowired service.

return $this->services['pimcore.data_object.grid_column_config.operator.factory.translate_value'] = new \Pimcore\DataObject\GridColumnConfig\Operator\Factory\TranslateValueFactory(${($_ = isset($this->services['Pimcore\Translation\Translator']) ? $this->services['Pimcore\Translation\Translator'] : $this->getTranslatorService()) && false ?: '_'});
