<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore_admin.webservice.service' shared autowired service.

return $this->services['pimcore_admin.webservice.service'] = new \Pimcore\Model\Webservice\Service();
