<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.data_object.grid_column_config.value.factory.objects' shared autowired service.

return $this->services['pimcore.data_object.grid_column_config.value.factory.objects'] = new \Pimcore\DataObject\GridColumnConfig\Value\Factory\DefaultValueFactory('Pimcore\\DataObject\\GridColumnConfig\\Value\\Objects');
