<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers'] = new \Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers(${($_ = isset($this->services['Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver']) ? $this->services['Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver'] : $this->getTokenStorageUserResolverService()) && false ?: '_'});
