<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore_admin.serializer' shared autowired service.

return $this->services['pimcore_admin.serializer'] = new \Symfony\Component\Serializer\Serializer(array(0 => new \Pimcore\Bundle\AdminBundle\Serializer\Normalizer\ReferenceLoopNormalizer()), array(0 => new \Symfony\Component\Serializer\Encoder\JsonEncoder()));
