<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.cache.core.pool.array' shared autowired service.

$this->services['pimcore.cache.core.pool.array'] = $instance = new \Pimcore\Cache\Pool\SymfonyAdapterProxy(${($_ = isset($this->services['pimcore.cache.core.symfony_adapter.array']) ? $this->services['pimcore.cache.core.symfony_adapter.array'] : $this->load('getPimcore_Cache_Core_SymfonyAdapter_ArrayService.php')) && false ?: '_'}, 2419200);

$instance->setLogger(${($_ = isset($this->services['monolog.logger.cache']) ? $this->services['monolog.logger.cache'] : $this->getMonolog_Logger_CacheService()) && false ?: '_'});

return $instance;
