<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Tool\RestClient' shared autowired service.

return $this->services['Pimcore\Tool\RestClient'] = new \Pimcore\Tool\RestClient(${($_ = isset($this->services['pimcore.http_client']) ? $this->services['pimcore.http_client'] : $this->load('getPimcore_HttpClientService.php')) && false ?: '_'});
