<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.cbzp4i_' shared service.

return $this->services['service_locator.cbzp4i_'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('configWriter' => function () {
    $f = function (\Pimcore\Config\ReportConfigWriter $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Config\ReportConfigWriter']) ? $this->services['Pimcore\Config\ReportConfigWriter'] : $this->load('getReportConfigWriterService.php')) && false ?: '_'});
}));
