<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\DataObject\Consent\Service' shared autowired service.

return $this->services['Pimcore\DataObject\Consent\Service'] = new \Pimcore\DataObject\Consent\Service();
