<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.hlydgjp' shared service.

return $this->services['service_locator.hlydgjp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('eventDispatcher' => function () {
    return ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'};
}, 'importService' => function () {
    $f = function (\Pimcore\DataObject\Import\Service $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\DataObject\Import\Service']) ? $this->services['Pimcore\DataObject\Import\Service'] : $this->load('getService4Service.php')) && false ?: '_'});
}, 'localeService' => function () {
    $f = function (\Pimcore\Localization\Locale $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Localization\Locale']) ? $this->services['Pimcore\Localization\Locale'] : $this->load('getLocaleService.php')) && false ?: '_'});
}));
