<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'swiftmailer.mailer.newsletter_mailer' shared service.

return $this->services['swiftmailer.mailer.newsletter_mailer'] = new \Swift_Mailer(${($_ = isset($this->services['swiftmailer.mailer.newsletter_mailer.transport']) ? $this->services['swiftmailer.mailer.newsletter_mailer.transport'] : $this->load('getSwiftmailer_Mailer_NewsletterMailer_TransportService.php')) && false ?: '_'});
