<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.oasldpk' shared service.

return $this->services['service_locator.oasldpk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('configProvider' => function () {
    $f = function (\Pimcore\Analytics\Piwik\Config\ConfigProvider $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider']) ? $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] : $this->services['Pimcore\Analytics\Piwik\Config\ConfigProvider'] = new \Pimcore\Analytics\Piwik\Config\ConfigProvider()) && false ?: '_'});
}));
