<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.yqmz4h5' shared service.

return $this->services['service_locator.yqmz4h5'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('documentRouteHandler' => function () {
    $f = function (\Pimcore\Routing\Dynamic\DocumentRouteHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Routing\Dynamic\DocumentRouteHandler']) ? $this->services['Pimcore\Routing\Dynamic\DocumentRouteHandler'] : $this->getDocumentRouteHandlerService()) && false ?: '_'});
}, 'eventDispatcher' => function () {
    return ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'};
}));
