<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.gvtprlr' shared service.

return $this->services['service_locator.gvtprlr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('service' => function () {
    $f = function (\Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Assets $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Assets']) ? $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Assets'] : $this->load('getAssetsService.php')) && false ?: '_'});
}));
