<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.bwebjcr' shared service.

return $this->services['service_locator.bwebjcr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('kernel' => function () {
    return ${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', /* ContainerInterface::NULL_ON_INVALID_REFERENCE */ 2)) && false ?: '_'};
}, 'siteConfigProvider' => function () {
    $f = function (\Pimcore\Analytics\Google\Config\SiteConfigProvider $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Analytics\Google\Config\SiteConfigProvider']) ? $this->services['Pimcore\Analytics\Google\Config\SiteConfigProvider'] : $this->load('getSiteConfigProviderService.php')) && false ?: '_'});
}));
