<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Controller\ArgumentValueResolver\TemplateVarsValueResolver' shared autowired service.

return $this->services['Pimcore\Controller\ArgumentValueResolver\TemplateVarsValueResolver'] = new \Pimcore\Controller\ArgumentValueResolver\TemplateVarsValueResolver(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\TemplateVarsResolver']) ? $this->services['Pimcore\Http\Request\Resolver\TemplateVarsResolver'] : $this->load('getTemplateVarsResolverService.php')) && false ?: '_'});
