<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Http\Request\Resolver\TemplateResolver' shared autowired service.

return $this->services['Pimcore\Http\Request\Resolver\TemplateResolver'] = new \Pimcore\Http\Request\Resolver\TemplateResolver(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Controller\Config\ConfigNormalizer']) ? $this->services['Pimcore\Controller\Config\ConfigNormalizer'] : $this->services['Pimcore\Controller\Config\ConfigNormalizer'] = new \Pimcore\Controller\Config\ConfigNormalizer(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'})) && false ?: '_'});
