<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Http\Request\Resolver\ViewModelResolver' shared autowired service.

return $this->services['Pimcore\Http\Request\Resolver\ViewModelResolver'] = new \Pimcore\Http\Request\Resolver\ViewModelResolver(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Http\Request\Resolver\TemplateVarsResolver']) ? $this->services['Pimcore\Http\Request\Resolver\TemplateVarsResolver'] : $this->load('getTemplateVarsResolverService.php')) && false ?: '_'});
