<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Controller\ArgumentValueResolver\ViewModelValueResolver' shared autowired service.

return $this->services['Pimcore\Controller\ArgumentValueResolver\ViewModelValueResolver'] = new \Pimcore\Controller\ArgumentValueResolver\ViewModelValueResolver(${($_ = isset($this->services['Pimcore\Http\Request\Resolver\ViewModelResolver']) ? $this->services['Pimcore\Http\Request\Resolver\ViewModelResolver'] : $this->load('getViewModelResolverService.php')) && false ?: '_'});
