<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Templating\Helper\WebLink' shared autowired service.

return $this->services['Pimcore\Templating\Helper\WebLink'] = new \Pimcore\Templating\Helper\WebLink(${($_ = isset($this->services['twig.extension.weblink']) ? $this->services['twig.extension.weblink'] : $this->getTwig_Extension_WeblinkService()) && false ?: '_'});
