<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPnhyjy1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPnhyjy1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPnhyjy1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPnhyjy1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPnhyjy1\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pnhyjy1',
    'container.build_id' => '0acac785',
    'container.build_time' => 1531140853,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPnhyjy1');
