<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTdduiyg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTdduiyg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTdduiyg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTdduiyg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTdduiyg\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tdduiyg',
    'container.build_id' => '832174a4',
    'container.build_time' => 1531193009,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTdduiyg');
